import React from 'react';
import { Sparkles } from 'lucide-react';

interface ModelBadgeProps {
    model?: string;
    provider?: string;
    className?: string;
}

export const ModelBadge: React.FC<ModelBadgeProps> = ({ model, provider, className = '' }) => {
    if (!model) return null;

    // Extract model name from full ID (e.g., "openai/gpt-4o-mini" -> "GPT-4o Mini")
    const displayName = model
        .split('/').pop()
        ?.replace(/-/g, ' ')
        ?.replace(/\b\w/g, l => l.toUpperCase())
        ?.replace(':free', ' (Free)')
        || model;

    return (
        <div className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-purple-500/10 border border-purple-500/20 text-xs text-purple-300 ${className}`}>
            <Sparkles className="w-3 h-3" />
            <span>Generated by <span className="font-medium text-purple-200">{displayName}</span></span>
        </div>
    );
};

export default ModelBadge;
